### PR TITLE
Add the ability to use functions in order to get the token or make a payment request

### PR DESCRIPTION
**Pull request by Destreyf**
This allows users to use their own HTTP Libraries, add arbitrary headers and customize the output from whatever backend they are using.

Documentation of how to use has been added to the README.

### CODE REVIEW

**Comment by Destreyf** [comment]
I've also updated some of the readme to use markdown code blocks to allow syntax highlighting to occur within the readme file.

**Comment by Destreyf** [comment]
This will close #46 when its merged.

**Comment by srikanthonl** [comment]
Awesome. 👍 
A small question. I believe the createPurchase method can expect nonce alone and chargeAmount can be omitted. Because when the consumer component itself inputs chargeAmount, I don't see why we should send the chargeAmount sent by it, back to it. What do you think?
This is how the @Input() can be declared:
@Input() createPurchase: Function = (nonce) => this.service.createPurchase(this.createPurchaseURL, nonce, this.chargeAmount);

  confirmPay(): void {
    this.showDropinUI = false;
    this.createPurchase(this.nonce)
      .subscribe((status: any) => {
        if (status.errors) {
          this.errorMessage = status.message;
          this.showDropinUI = true;
          this.generateDropInUI();
        }
        this.paymentStatus.emit(status);
      });
  }

and the function that will be sent as input:
  createPurchase: Function = (nonce: string) => {
    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });
    return this.http
    .post('api/braintree/createpurchase', { nonce: nonce, chargeAmount: this.chargeAmount }, { 'headers': headers })
      .map((response: any) => {
        return response;
      });
  }

**Comment by Destreyf** [comment]
@srikanthonl 

After looking at it for a bit and thinking it through (I've been a little busy the last couple days).  I think that should work, however the reason i was passing "paymentAmount" to the function call is their function can (and probably will) live outside of the component itself, so unless they manually store that amount, they may not know which amount they're processing for.

A quick example of this is if i have 3 instances on a page named "donate" that are "Amount 1", "Amount 2" and "Amount 3", and i have a function of my own called "chargePayment" that function can be bound to all 3 amounts, and if you do `<ngx-braintree ... [createPurchase]="chargePayment.bind(this)" ...></ngx-braintree>` when the create purchase is called from within ngx-braintree, the `.bind(this)` forces the function to run in the context of `donate` and not `ngx-braintree`, this means that the function does not know what `this.chargeAmount` is, and will either throw an undefined error, or result in an invalid transaction using braintree.

We could force them to know which component was pressed by having them handle it on their side for each function/item that's used but having it exist in the arguments as a call should simplify the overall deployment.

**Comment by srikanthonl** [comment]
Agreed. Having the `chargeAmount` to exist in arguments is a preferred approach to forcing the user to remember the amount.

**Pull request merged**
