### PR TITLE
Adding Charge Amount

### PR DESCRIPTION
**Pull request by madhavabhyankar**
This will assist in passing the dollar amount dynamically.  Referencing #36 
See Example below:
`<ngx-braintree 
                    [clientTokenURL]="'api/salerecord/braintree/getclienttoken'" 
                    [createPurchaseURL]="'api/salerecord/braintree/createpurchase'" 
                    (paymentStatus)="onPaymentStatus($event)"
                               [chargeAmount]="50.445">
                </ngx-braintree>`

And the Data posted to create purchase is:
`public class Nonce
    {
        public string nonce;
        public decimal chargeAmount;
        public Nonce(string nonce, decimal chargeAmount)
        {
            this.nonce = nonce;
            this.chargeAmount = chargeAmount;
        }

    }`

### CODE REVIEW

**Comment by dela-dels** [comment]
how do i pass a value/variable to the chargeAmount? do i do somthing like this?

```
<ngx-braintree [clientTokenURL]="'api/salerecord/braintree/getclienttoken'" [createPurchaseURL]="'api/salerecord/braintree/createpurchase'" (paymentStatus)="onPaymentStatus($event)" [chargeAmount]={{ order.amount }}> </ngx-braintree>

```

**Comment by dela-dels** [comment]
@madhavabhyankar  is this working now? or yet to be published?

**Comment by madhavabhyankar** [comment]
@dela-dels 
the charge amount should tied to the model 

`[chargeAmount]="order.amount"`

Also the pull request has not been merged - so its not published yet.

**Comment by dela-dels** [comment]
@madhavabhyankar oh okay. thanks. i really need this for my final year project in school.
i hope it gets merged soon.

**Comment by madhavabhyankar** [comment]
You can always fork and copy my changes.

**Pull request merged**
