### PR TITLE
Updating version 5.1.x so it works with Ionic v3 Production Builds.

### PR DESCRIPTION
**Pull request by selected-pixel-jameson**
When trying to use this library in Ionic v3 it was working great until I tried to do a production build. Production builds in Ionic use the Ahead-of-Time compiling and various other settings, but I was getting the following error. 

` Error during template compile of 'NgxBraintreeModule' Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule' 'NgModule' calls 'ɵmakeDecorator'. 

I did some research and found this article github issue. https://github.com/angular/angular-cli/issues/3854. Which stated that a solution for this is to including the paths for the angular node_modules in the tsconfig.ts file.This then packages the project without the node_modules directory. Once I did this and copied the packaged files over to my Ionic project I was able to do a production build and run the app successfully.

### CODE REVIEW

**Comment by srikanthonl** [comment]
Hi, Thank you for this. Is this PR a fix for the **5.1.x branch?**

**Comment by selected-pixel-jameson** [comment]
@srikanthonl Yes it's a fix for the 5.1 branch. Sorry that it took me awhile to get back to you.

**Comment by selected-pixel-jameson** [comment]
Can we resolve the conflicts to get this merged successfully? I'm assuming it's just formatting issues.

**Comment by srikanthonl** [comment]
@selected-pixel-jameson sorry for this long delay. I wasn't well and back online few days ago. Will review the pull request soon. Thank you.

**Comment by srikanthonl** [comment]
@selected-pixel-jameson As said earlier this is your pull request for the 5.1 branch. 

But, I see that your PR has the Angular version updated from 5.1.0 to 6.0.7 and RxJS version from 5.5.5 to 6.2.1, when there is already a branch 6.1.x with similar versions. Version 5.x of ngx-braintree (branch 5.1.x) is meant for Angular 5 applications. If you intend to use Angular 6.x and RxJS 6.x (as your PR is updating from version 5 to 6) please use the code base from the master branch or the 6.1.x branch or use the command npm install ngx-braintree which will install the latest version which supports Angular 6 and RxJS 6 applications.

**Pull request closed without merging**
